repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
        - --hook-config=--use-standard-markers=true   
        - --args=--config=.terraform-docs.yml
    - id: terraform_trivy
      args:
        - --args=--skip-dirs=".infracost"
